### ISSUE TITLE
Company Create "Request Failed with status code 415 (Unsupported Media Type)" (Patch Included)

### ISSUE THREAD

**Issue by perrymartijena** [pmanca/hubspot-api-wrapper#14]
Hey guys,

I've been using the hubspot-api-wrapper, and when creating a company getting a 415 Unsupported Media Type response. It's due to the data not being submitted as JSON. I included the change below.

From company.js lines 15-22 in the create function:
`var token = hubCache.get("config").value
			return axios.post(endpoint,properties,
				{headers: {"Authorization": "Bearer " + token, "content-type": "application/json" }
			}).then(response => {
				return response
			}).catch(err => {
				return err
			})`

and also from company.js lines 142-150 in the addContactToCompany function:
`if(hubCache.get("config").type == "hapikey"){
			endpoint += `?hapikey=` + hubCache.get("config").value
			return axios.put(endpoint,{},
				{headers: {"content-type": "application/json"}
			}).then(response =>{
				return response
			}).catch(err =>{
				return err
			})`

Hope you guys can implement this so I can add hubspot-api-wrapper back to my package.json instead of having my custom version running.

Thanks

**Comment by pmanca** [comment]
@perrymartijena  I really appreciate you reaching out for the advice on how to better improve the wrapper.  I just added the changes you suggested above and ran it through the mocha tests to confirm everything was working on my end.  This should be resolved now. Please let me know if you run into anything else.
